// Field names below mirror the backend exactly (Backend/data/scenarios.json,
// Backend/data/traces/*.json, Backend/data/classifications/*.json). Category
// and severity are typed as `string`, not string-literal unions: the backend
// vocabulary is generated by an LLM per agent and must not be hardcoded here.

export interface ToolParameterSchema {
  type: string
  properties?: Record<string, { type: string; description?: string }>
  required?: string[]
  [key: string]: unknown
}

export interface Tool {
  name: string
  description: string
  parameters: ToolParameterSchema
}

export interface AgentConfig {
  agent_name: string
  domain: string
  system_prompt: string
  purpose: string
  rules: string[]
  tools: Tool[]
}

export interface Scenario {
  id: string
  category: string
  description: string
  user_input: string
  expected_safe_behavior: string
  severity: string
}

export interface ToolOutput {
  tool_name: string
  status: string
  result: Record<string, unknown>
}

export interface FunctionCallEvent {
  turn: number
  action: 'function_call'
  name: string
  args: Record<string, unknown>
  tool_output: ToolOutput
}

export interface TextResponseEvent {
  turn: number
  action: 'text_response'
  content: string
}

export type TraceEvent = FunctionCallEvent | TextResponseEvent | (Record<string, unknown> & { turn: number; action: string })

export interface MockToolLogEntry {
  sequence: number
  tool_name: string
  arguments: Record<string, unknown>
  outcome: string
  result: Record<string, unknown>
}

export interface TraceExecution {
  status: string
  turns_used: number
  final_response: string
  trace: TraceEvent[]
}

export interface Trace {
  scenario_id: string
  category: string
  severity: string
  description: string
  user_input: string
  expected_safe_behavior: string
  execution: TraceExecution
  mock_tool_log: MockToolLogEntry[]
}

export interface Classification {
  scenario_id?: string
  classification: string // "safe" | "unsafe" in current backend vocabulary
  failure_category: string | null
  severity: string // "none" when safe; low/medium/high/critical (or other) when unsafe
  reason: string
}

export interface ScenarioResult extends Scenario {
  trace: Trace | null
  classification: Classification | null
}

export type RunStatus = 'queued' | 'executing' | 'classifying' | 'completed' | 'failed'

export interface ScenariosStatus {
  scenario_count: number
  stale: boolean
  current_agent_name: string | null
  generated_for_agent_name: string | null
}

export interface RunState {
  id: string
  status: RunStatus
  started_at: string
  finished_at: string | null
  total: number
  executed: number
  classified: number
  errors: string[]
  error: string | null
}

export type GenerationStatus = 'queued' | 'running' | 'completed' | 'failed'

export interface GenerationJob {
  id: string
  status: GenerationStatus
  stage: string | null
  categories_total: number
  categories_done: string[]
  category_errors: Record<string, string>
  scenario_count: number | null
  cleared_stale_results: number | null
  started_at: string
  finished_at: string | null
  error: string | null
}
